print('¿Te cuento algunos chistes? Presiona ENTER ')
input()
print('¿Qué sale de la cruza entre un mono y un pato?')
input()
print('¡un monopatín!')
input()
print('¿Por qué vuelan los pájaros pa\'l sur?')
input()
print('¡Porque caminando tardarían muchísimo!')
input()
print('¿En qué se parecen una familia, un bombero y un barco?')
input()
print(" No sé, ¿en qué se parecen?")
input()
print('En que el bombero y el barco tienen casco.')
input()
print(' ¿y la familia?' , end='')
print()
input()
print('Bien, gracias.')
